In [3]:
import numpy as np

In [6]:
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr

array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
       [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
       [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
       [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
       [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
       [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])

In [137]:
a = np.unique(arr,axis=1)

#Y = np.unique(arr,axis=1)

#b = np.bincount(np.array(a[0]))
#arr.shape[0]
#ind = np.array(lambda b : np.bincount(np.array(a[i] for i in arr.shape[0])))

bin_length = arr.shape[1]+1
bin_arr_sized = []
final = []
for i in range(0,arr.shape[0]):
    
    bin_arr = (np.array(a[i]))
    bin_arr_sized=np.bincount(bin_arr,minlength=bin_length)
    final =np.concatenate((final,bin_arr_sized)).astype(int)
    #print("Final",final)
  #  final = np.vstack((a,b))
   # type(bin_arr_sized)
     #ans = ans.append(np.bincount(np.array(a[i])))
        
  #  ans = np.bincount(np.array(a[i]))
final = final.reshape(6,11).astype(int)
final = final[:,1:]
final





array([[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
       [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
       [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
       [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
       [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]])

array([[0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [2],
       [0],
       [0],
       [2],
       [1]])